#!/bin/bash

# quick little script just to make a new post with the right date

FDATE=$(date "+%Y-%m-%d")
FILENAME=$FDATE-$1.markdown

echo -e "---\nlayout: post\ntitle: $1\ncategories: blog\n---" > $FILENAME
git add filename

